# Generated by Django 5.2.8 on 2025-11-24 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_names', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Phytochemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=255)),
                ('compound_class', models.CharField(blank=True, max_length=255)),
                ('biological_activity', models.CharField(blank=True, max_length=255)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phytochemicals', to='main.plant')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature', to='main.plant')),
            ],
        ),
    ]
